name: Build Zed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install system dependencies (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \ # Важно для компиляции
            libx11-dev \
            libxi-dev \
            libgdk-pixbuf2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libssl-dev \
            pkg-config \
            cmake \
            ninja-build 

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: cargo build --release

      - name: Run tests (optional)
        run: cargo test

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: zed-build
          path: target/release/zed
